apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-scipy
  labels:
    app: jupyter-scipy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-scipy
  template:
    metadata:
      labels:
        app: jupyter-scipy
    spec:
      containers:
      - name: scipy-notebook
        image: jupyter/scipy-notebook:latest
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  type: NodePort
  selector:
    app: jupyter-scipy
  ports:
  - protocol: TCP
    nodePort: 8888
    port: 8888
    targetPort: 8888